services:
  backend:
    build: ./server
    container_name: backend1
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: http://13.60.33.20:5000/api
    container_name: frontend1
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend
