version: "3.9"

services:
  backend:
    build: ./server
    container_name: backend1
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"

  frontend:
    build: ./client
    container_name: frontend1
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
