name: build-and-lint

on:
  push:
    branches: [ "master", "ayush" ]
  pull_request:
    branches: [ "master", "ayush" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: server
        run: npm ci

      - name: Lint backend code
        working-directory: server
        run: npm run lint -- --max-warnings=0

      - name: Install frontend dependencies
        working-directory: client
        run: npm ci

      - name: Lint frontend code
        working-directory: client
        run: npm run lint -- --max-warnings=0

      - name: Build backend Docker image
        run: docker build -t backend ./server

      - name: Build frontend Docker image
        run: docker build -t frontend ./client

  deploy:
    needs: build-and-lint
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Write SSH key
        run: |
          echo "${EC2_KEY}" > ec2_key.pem
          chmod 600 ec2_key.pem
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Deploy on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_APP_DIR: ${{ secrets.EC2_APP_DIR }}
        run: |
          ssh -i ec2_key.pem ${EC2_USER}@${EC2_HOST} 'set -e; APP_DIR="${EC2_APP_DIR:-/home/ec2-user/devops}"; if [ ! -d "$APP_DIR/.git" ]; then rm -rf "$APP_DIR"; git clone https://github.com/Ayush701-code-zm/devops.git "$APP_DIR"; fi; cd "$APP_DIR"; git fetch --all; git reset --hard origin/${{ github.ref_name }}; docker compose up -d --build; docker image prune -f; docker compose ps' 